server {
    listen 4444;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:4445/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 100M;
        proxy_read_timeout 600s;
    }

    location /health {
        proxy_pass http://127.0.0.1:4445/health;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
